<?php

use Illuminate\Database\Seeder;

class FamilyTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \DB::table('family_types')->insert([
            'name'=>'SLIDING',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'FLUSH',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'PVC',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'SLIDING',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>' AWNING',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'FIXED',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'HUNG',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'CASEMENT',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'FURNITURE',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'ELECTRICAL FIXTURE',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'FIRE ALARM',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'CATV',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'LAMP',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'FLUORESCENT LAMP',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'WALL LAMP',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'DOWN LIGHT',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'GENERATOR & TRANSFORMATION',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'CIRCUIT BREAKER',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'PANEL BOARD',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'APPLIANCES',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'SWITCH',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'METER',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'CHANNEL CABLE',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'LADDER',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'OUTLET',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'METER',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'JUNCTION BOX',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'WATER CLOSET',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'URINALS',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'SINKS',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'SHOWERS',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'DRAINS',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'BATHTUBS',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'WATER HEATER',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'LAVATORY',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'SEPTINK TANK',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'SPRINKLER',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'SMOKE DETECTOR',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'FIRE HOSE CABINET',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'FIRE EXTINGUISHER CABINET',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'SIGNAGES',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'ROUND',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'RECTANGULAR',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'OVAL',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'MULTI-SHAPE',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
        \DB::table('family_types')->insert([
            'name'=>'',
            'category_id'=>0,
            'user_id'=>1,
            'is_lock'=>1
        ]);
    }
}
